var questions = [
  {label:"Quelle est la capitale du Pérou ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r1"},
  {label:"Quel est le symbole chimique de l'Arsenic ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"Qui a écrit Charlie et la chocolaterie ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r2"},
  {label:"Quel joueur de football a marqué le premier but en or de l'histoire de la coupe du monde ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle est la plus grande île de la Méditerranée ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r2"},
  {label:"Qu'est-ce qui a provoqué une dizaine de milliers de morts en France pendant l'été 2003 ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r4"},
  {label:"Sur quel continent vit le kinkajou ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r1"},
  {label:"Comment s'appelle une personne qui pratique un sport sans toucher une rémunération ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quel animal est associé aux Baskerville dans un roman de Conan Doyle ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r2"},
  {label:"Au poker, que fait un joueur quand il fait tapis? ", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r1"},
  {label:"De quel ours héros de dessin animé Coco Lapin est-il l'ami ? ", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r4"},
  {label:"Comment s'appelait la première épouse de Napoléon Bonaparte ? ", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r1"},
  {label:"Dans quelle partie du corps se trouve la patella ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"Lequel de ces films d'Arnold Schwarzenegger est sorti en premier ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r2"},
  {label:"Quel livre de la série Harry Potter J.K. Rowling a-t-elle écrit en premier ? ", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r4"},
  {label:"En 2011, lequel de ces pays a consacré la plus grosse partie de son PIB à la santé ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r1"},
  {label:"Laquelle de ces planètes est la plus chaude ? ", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r2"},
  {label:"Lequel de ces héros de jeu vidéo est apparu le premier ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r1"},
  {label:"Quel pays reçoit le plus grand nombre de demandes d'immigration de français ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r4"},
  {label:"Dans l'histoire du cinéma, combien de films ont remporté 11 Oscars ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle feuille est au centre du drapeau canadien ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r3"},
  {label:"En 1936, combien de semaines de congés payés ont-elles été accordées aux Français ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r2"},
  {label:"Quel personnage de la mythologie grecque est l'héroïne d'une tragédie composée par Sophocle et modernisée par Anouilh ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r4"},
  {label:"Comment appelle-t-on les jeunes moules élevées en mytiliculture ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"Dans quelle ville s'est déroulée la finale du Mondial de football 2002 ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r4"},
  {label:"Comment appelle-t-on les habitants de l'île de Mayotte ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r3"},
  {label:"Dans quelle station de sports d'hiver les Bronzés ont-ils fait du ski ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r4"},
  {label:"Quelle île fut l'enjeu d'une lutte incessante entre les couronnes d'Angleterre et de France, de 1294 à 1630 ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r3"},
  {label:"A quel célèbre portrait Marcel Duchamps a-t-il ajouté une moustache et une barbichette en 1919 ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r1"},
  {label:"Dans quel pays africain le virus de la grippe aviaire a-t-il fait son apparition sur ce continent ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r4"},
  {label:"Quelle partie du stade de Berlin a été vendue aux supporters après la finale de la Coupe du Monde de football 2006 ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:"Dans quelle ville anglaise le tunnel sous la Manche débouche-t-il ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r1"},
  {label:"Pour quel pays France Gall a-t-elle remporté le Concours Eurovision en 1965 ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle armée a envahi la Slovénie et la Croatie en 1991 ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r2"},
  {label:"Dans quelle ville se tient le plus grand festival théâtral de France ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r1"},
  {label:"Qu'est-ce qui mesure la résistance électrique ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r4"},
  {label:"En kitesurf, par quoi est-on tracté ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:"Avec quel pays le Chili a-t-il plus de 4000 km de frontières communes ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r4"},
  {label:"Qui joue le fan de Johnny Hallyday dans Jean-Philippe ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quel souverain français s'est opposé aux Suisses lors de la bataille de Marignan en 1515 ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r1"},
  {label:"Dans quel album, Tintin peut-il mettre en boîte le Capitaine Haddock, pour la première fois ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r4"},
  {label:"Quels poissons viennent se reproduire dans la mer des Sargasses ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quel sport a été codifié par les règles de Queensberry ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:" Dans quelle ville trouve-t-on la plus forte concentration bancaire au monde ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r1"},
  {label:"Quel animal est Skipper dans Madagascar ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r2"},
  {label:"Quel était le métier de Gandhi ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle est la dernière oeuvre achevée composée par Mozart, un opéra joué pour la 1ère fois 2 mois avant sa mort ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r1"},
  {label:"De quelle graine croquante pour l'apéritif, l'Iran est-il le premier producteur mondial ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quel sport a été marqué par la rivalité entre Eunice Barber et Carolina Klüft ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle est la nationalité de Shakira ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r1"},
  {label:"Quel édit, signé en 1598, a accordé la liberté religieuse aux protestants ?", unique: true , idTheme: "3", Type: "TXT",src:"",Answer: "r2"},
  {label:"Quel genre musical est né en Louisiane au début du XXème siècle ", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle est la température fixe et constante de l'ébullition de l'eau ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quel saut ne figure pas au programme du décathlon ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r3"},
  {label:"Dans quel pays se trouvent les villes de Madras et Bombay ?", unique: true , idTheme: "1", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quel comédien et humoriste avait créé les Resto du coeur, quelques mois avant son décès en 1986 ?", unique: true , idTheme: "2", Type: "TXT",src:"",Answer: "r2"},
  {label:"Qui était Nostradamus ?", unique: true , idTheme: "7", Type: "TXT",src:"",Answer: "r2"},
  {label:"Quelle lettre signe les méfaits de La Marque Jaune dans les aventures de Blake et Mortimer ?", unique: true , idTheme: "4", Type: "TXT",src:"",Answer: "r2"},
  {label:"Vie et nature : Combien y a-t-il de couleurs primaires ?", unique: true , idTheme: "7", Type: "TXT",src:"",Answer: "r2"},
  {label:"Au Japon, comment s'appelle l'art du pliage du papier ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r2"},
  {label:"Dans quelle ville se trouve la promenade des anglais ?", unique: true , idTheme: "7", Type: "TXT",src:"",Answer: "r3"},
  {label:"Quelle humanoïde virtuelle de 'Code Lyoko' est l'amie de Yumi, Odd, Ulrich et Jérémie ?", unique: true , idTheme: "7", Type: "TXT",src:"",Answer: "r4"},
  {label:"Pendant quelle guerre les taxis de la Marne sont-ils restés dans l'Histoire ?", unique: true , idTheme: "7", Type: "TXT",src:"",Answer: "r1"},
  {label:"Quel animal est l'emblème de Poufsouffle dans Harry Potter ?", unique: true , idTheme: "7", Type: "TXT",src:"",Answer: "r4"},
  {label:"Que sont les points qui composent un écran télé ou d'ordinateur ?", unique: true , idTheme: "5", Type: "TXT",src:"",Answer: "r3"},
  {label:"En cyclisme, qui porte le maillot arc-en-ciel ?", unique: true , idTheme: "6", Type: "TXT",src:"",Answer: "r2"}
];

var reponses = [
  {label:"Lima",idQuestion:1, unique:true, position:"r1",Type:"TXT"},
  {label:"Santiago", idQuestion:1,unique:true, position:"r2",Type:"TXT"},
  {label:"La Paz", idQuestion:1,unique:true, position:"r3",Type:"TXT"},
  {label:"Paita", idQuestion:1,unique:true, position:"r4",Type:"TXT"},

  {label:"Ar", idQuestion:2, unique:true, position:"r2",Type:"TXT"},
  {label:"Ag", idQuestion:2,unique:true, position:"r1",Type:"TXT"},
  {label:"As", idQuestion:2, unique:true, position:"r3",Type:"TXT"},
  {label:"At", idQuestion:2, unique:true, position:"r4",Type:"TXT"},

  {label:"Roald Dahl", idQuestion:3,unique:true, position:"r1",Type:"TXT"},
  {label:"J.K. Rowling",idQuestion:3, unique:true, position:"r2",Type:"TXT"},
  {label:"Charles Dickens",idQuestion:3, unique:true, position:"r3",Type:"TXT"},
  {label:"Victor Hugo",idQuestion:3, unique:true, position:"r4",Type:"TXT"},

  {label:"David Trezeguet", idQuestion:4,unique:true, position:"r1",Type:"TXT"},
  {label:"Didier Deschamps",idQuestion:4, unique:true, position:"r2",Type:"TXT"},
  {label:"Laurent Blanc",idQuestion:4, unique:true, position:"r3",Type:"TXT"},
  {label:"Zinédine Zidane",idQuestion:4, unique:true, position:"r4",Type:"TXT"},

  {label:"Marjorque", idQuestion:5, unique:true, position:"r2",Type:"TXT"},
  {label:"Sicile", idQuestion:5,unique:true, position:"r1",Type:"TXT"},
  {label:"Ibiza", idQuestion:5, unique:true, position:"r3",Type:"TXT"},
  {label:"Capri",idQuestion:5, unique:true, position:"r1",Type:"TXT"},

  {label:"Les requins", idQuestion:6, unique:true, position:"r2",Type:"TXT"},
  {label:"Les nazis", idQuestion:6,unique:true, position:"r1",Type:"TXT"},
  {label:"La famine", idQuestion:6, unique:true, position:"r3",Type:"TXT"},
  {label:"La canicule",idQuestion:6, unique:true, position:"r4",Type:"TXT"},

  {label:"Amérique du Sud", idQuestion:7, unique:true, position:"r2",Type:"TXT"},
  {label:"Europe", idQuestion:7,unique:true, position:"r1",Type:"TXT"},
  {label:"Asie", idQuestion:7, unique:true, position:"r3",Type:"TXT"},
  {label:"Amérique du Nord",idQuestion:7, unique:true, position:"r4",Type:"TXT"},

  {label:"Un arabe", idQuestion:8, unique:true, position:"r2",Type:"TXT"},
  {label:"Un russe", idQuestion:8,unique:true, position:"r1",Type:"TXT"},
  {label:"Un amateur", idQuestion:8, unique:true, position:"r3",Type:"TXT"},
  {label:"Un lapin",idQuestion:8, unique:true, position:"r4",Type:"TXT"},

  {label:"L'élépphant", idQuestion:9, unique:true, position:"r1",Type:"TXT"},
  {label:"Le chien", idQuestion:9,unique:true, position:"r2",Type:"TXT"},
  {label:"Le chat", idQuestion:9, unique:true, position:"r3",Type:"TXT"},
  {label:"Un russe",idQuestion:9, unique:true, position:"r4",Type:"TXT"},

  {label:"Il mise tout", idQuestion:10, unique:true, position:"r1",Type:"TXT"},
  {label:"Il abandonne", idQuestion:10,unique:true, position:"r2",Type:"TXT"},
  {label:"Il a vu un russe", idQuestion:10, unique:true, position:"r3",Type:"TXT"},
  {label:"Il vend son tapis",idQuestion:10, unique:true, position:"r4",Type:"TXT"},

  {label:"Le roi lion", idQuestion:11, unique:true, position:"r1",Type:"TXT"},
  {label:"Ichigo", idQuestion:11,unique:true, position:"r2",Type:"TXT"},
  {label:"Aladin", idQuestion:11, unique:true, position:"r3",Type:"TXT"},
  {label:"Winnie l'Ourson",idQuestion:11, unique:true, position:"r4",Type:"TXT"},

  {label:"Joséphine de Beauharnais", idQuestion:12, unique:true, position:"r1",Type:"TXT"},
  {label:"Duchesnois", idQuestion:12,unique:true, position:"r2",Type:"TXT"},
  {label:"Ivane Tarvana", idQuestion:12, unique:true, position:"r3",Type:"TXT"},
  {label:"Paullette Verdun",idQuestion:12, unique:true, position:"r4",Type:"TXT"},

  {label:"Les testicules", idQuestion:13, unique:true, position:"r1",Type:"TXT"},
  {label:"Le cou", idQuestion:13,unique:true, position:"r2",Type:"TXT"},
  {label:"Le genou", idQuestion:13, unique:true, position:"r3",Type:"TXT"},
  {label:"La cuisse",idQuestion:13, unique:true, position:"r4",Type:"TXT"},

  {label:"Terminator", idQuestion:14, unique:true, position:"r1",Type:"TXT"},
  {label:"Conan le destructeur", idQuestion:14,unique:true, position:"r2",Type:"TXT"},
  {label:"Total recall", idQuestion:14, unique:true, position:"r3",Type:"TXT"},
  {label:"Junior",idQuestion:14, unique:true, position:"r4",Type:"TXT"},

  {label:"Harry Potter et la chambre des secrets", idQuestion:15, unique:true, position:"r1",Type:"TXT"},
  {label:"Harry Potter et les reliques de la mort", idQuestion:15,unique:true, position:"r2",Type:"TXT"},
  {label:"Harry Potter et la coupe de feu", idQuestion:15, unique:true, position:"r3",Type:"TXT"},
  {label:"Harry Potter à l'école des sorciers",idQuestion:15, unique:true, position:"r4",Type:"TXT"},

  {label:"Le Libéria", idQuestion:16, unique:true, position:"r1",Type:"TXT"},
  {label:"La chine", idQuestion:16,unique:true, position:"r2",Type:"TXT"},
  {label:"Les Etats Unis", idQuestion:16, unique:true, position:"r3",Type:"TXT"},
  {label:"Le congos",idQuestion:16, unique:true, position:"r4",Type:"TXT"},

  {label:"Jupiter", idQuestion:17, unique:true, position:"r1",Type:"TXT"},
  {label:"Vénus", idQuestion:17,unique:true, position:"r2",Type:"TXT"},
  {label:"Uranus", idQuestion:17, unique:true, position:"r3",Type:"TXT"},
  {label:"Saturne",idQuestion:17, unique:true, position:"r4",Type:"TXT"},

  {label:"Mega Man", idQuestion:18, unique:true, position:"r1",Type:"TXT"},
  {label:"Super Man", idQuestion:18,unique:true, position:"r2",Type:"TXT"},
  {label:"Russe Man", idQuestion:18, unique:true, position:"r3",Type:"TXT"},
  {label:"One punch Man",idQuestion:18, unique:true, position:"r4",Type:"TXT"},

  {label:"La Russie", idQuestion:19, unique:true, position:"r1",Type:"TXT"},
  {label:"La Belgique", idQuestion:19,unique:true, position:"r2",Type:"TXT"},
  {label:"Les Etats-Unis", idQuestion:19, unique:true, position:"r3",Type:"TXT"},
  {label:"Le Canada",idQuestion:19, unique:true, position:"r4",Type:"TXT"},

  {label:"1", idQuestion:20, unique:true, position:"r1",Type:"TXT"},
  {label:"2", idQuestion:20,unique:true, position:"r2",Type:"TXT"},
  {label:"3", idQuestion:20, unique:true, position:"r3",Type:"TXT"},
  {label:"4",idQuestion:20, unique:true, position:"r4",Type:"TXT"},

  {label:"Une feuille de chêne", idQuestion:21, unique:true, position:"r1",Type:"TXT"},
  {label:"Une feuille d'hêtre", idQuestion:21,unique:true, position:"r2",Type:"TXT"},
  {label:"Une feuille d'érable", idQuestion:21, unique:true, position:"r3",Type:"TXT"},
  {label:"Une feuille de vigne",idQuestion:21, unique:true, position:"r4",Type:"TXT"},

  {label:"1 semaine", idQuestion:22, unique:true, position:"r1",Type:"TXT"},
  {label:"2 semaines", idQuestion:22,unique:true, position:"r2",Type:"TXT"},
  {label:"3 semaines", idQuestion:22, unique:true, position:"r3",Type:"TXT"},
  {label:"4 semaines",idQuestion:22, unique:true, position:"r4",Type:"TXT"},

  {label:"Andromède", idQuestion:23, unique:true, position:"r1",Type:"TXT"},
  {label:"Atalante", idQuestion:23,unique:true, position:"r2",Type:"TXT"},
  {label:"Médée", idQuestion:23, unique:true, position:"r3",Type:"TXT"},
  {label:"Antigone",idQuestion:23, unique:true, position:"r4",Type:"TXT"},

  {label:"Le barget", idQuestion:24, unique:true, position:"r1",Type:"TXT"},
  {label:"Le bouillon", idQuestion:24,unique:true, position:"r2",Type:"TXT"},
  {label:"Le naissain", idQuestion:24, unique:true, position:"r3",Type:"TXT"},
  {label:"Le vuttal",idQuestion:24, unique:true, position:"r4",Type:"TXT"},

  {label:"Shanghaï", idQuestion:25, unique:true, position:"r1",Type:"TXT"},
  {label:"Séoul", idQuestion:25,unique:true, position:"r2",Type:"TXT"},
  {label:"Manille", idQuestion:25, unique:true, position:"r3",Type:"TXT"},
  {label:"Tokyo",idQuestion:25, unique:true, position:"r4",Type:"TXT"},

  {label:"Les Mayottais", idQuestion:26, unique:true, position:"r1",Type:"TXT"},
  {label:"Les Mayens", idQuestion:26,unique:true, position:"r2",Type:"TXT"},
  {label:"Les Mahorais", idQuestion:26, unique:true, position:"r3",Type:"TXT"},
  {label:"Les Mayottes",idQuestion:26, unique:true, position:"r4",Type:"TXT"},

  {label:"Alpe d'Huez", idQuestion:27, unique:true, position:"r1",Type:"TXT"},
  {label:"Tignes", idQuestion:27,unique:true, position:"r2",Type:"TXT"},
  {label:"La Plagne", idQuestion:27, unique:true, position:"r3",Type:"TXT"},
  {label:"Val-d'Isère",idQuestion:27, unique:true, position:"r4",Type:"TXT"},

  {label:"Ouessant", idQuestion:28, unique:true, position:"r1",Type:"TXT"},
  {label:"Belle-île", idQuestion:28,unique:true, position:"r2",Type:"TXT"},
  {label:"Ré", idQuestion:28, unique:true, position:"r3",Type:"TXT"},
  {label:"Groix",idQuestion:28, unique:true, position:"r4",Type:"TXT"},

  {label:"La Joconde", idQuestion:29, unique:true, position:"r1",Type:"TXT"},
  {label:"La jeune fille à la perle", idQuestion:29,unique:true, position:"r2",Type:"TXT"},
  {label:"Portrait de Martin Luther", idQuestion:29, unique:true, position:"r3",Type:"TXT"},
  {label:"La Vénus d'Urbin",idQuestion:29, unique:true, position:"r4",Type:"TXT"},

  {label:"Congo", idQuestion:30, unique:true, position:"r1",Type:"TXT"},
  {label:"Kenya", idQuestion:30,unique:true, position:"r2",Type:"TXT"},
  {label:"Somalie", idQuestion:30, unique:true, position:"r3",Type:"TXT"},
  {label:"Nigéria",idQuestion:30, unique:true, position:"r4",Type:"TXT"},

  {label:"Les sièges", idQuestion:31, unique:true, position:"r1",Type:"TXT"},
  {label:"Les filets des buts", idQuestion:31,unique:true, position:"r2",Type:"TXT"},
  {label:"La pelouse", idQuestion:31, unique:true, position:"r3",Type:"TXT"},
  {label:"Les éclairages",idQuestion:31, unique:true, position:"r4",Type:"TXT"},

  {label:"Folkestone", idQuestion:32, unique:true, position:"r1",Type:"TXT"},
  {label:"Lydd", idQuestion:32,unique:true, position:"r2",Type:"TXT"},
  {label:"Douvres", idQuestion:32, unique:true, position:"r3",Type:"TXT"},
  {label:"Fairlight",idQuestion:32, unique:true, position:"r4",Type:"TXT"},

  {label:"France", idQuestion:33, unique:true, position:"r1",Type:"TXT"},
  {label:"Suisse", idQuestion:33,unique:true, position:"r2",Type:"TXT"},
  {label:"Luxembourg", idQuestion:33, unique:true, position:"r3",Type:"TXT"},
  {label:"Belgique",idQuestion:33, unique:true, position:"r4",Type:"TXT"},

  {label:"L'armée bulgare", idQuestion:34, unique:true, position:"r1",Type:"TXT"},
  {label:"L'armée yougoslave", idQuestion:34,unique:true, position:"r2",Type:"TXT"},
  {label:"L'armée grecque", idQuestion:34, unique:true, position:"r3",Type:"TXT"},
  {label:"L'armée russe",idQuestion:34, unique:true, position:"r4",Type:"TXT"},

  {label:"Avignon", idQuestion:35, unique:true, position:"r1",Type:"TXT"},
  {label:"Saint-Malo", idQuestion:35,unique:true, position:"r2",Type:"TXT"},
  {label:"Dunkerque", idQuestion:35, unique:true, position:"r3",Type:"TXT"},
  {label:"Toulouse",idQuestion:35, unique:true, position:"r4",Type:"TXT"},

  {label:"Les décibels", idQuestion:36, unique:true, position:"r1",Type:"TXT"},
  {label:"Les volts", idQuestion:36,unique:true, position:"r2",Type:"TXT"},
  {label:"Les ampères", idQuestion:36, unique:true, position:"r3",Type:"TXT"},
  {label:"Les ohms",idQuestion:36, unique:true, position:"r4",Type:"TXT"},

  {label:"Un bateau", idQuestion:37, unique:true, position:"r1",Type:"TXT"},
  {label:"Une voile", idQuestion:37,unique:true, position:"r2",Type:"TXT"},
  {label:"Un cerf-volant", idQuestion:37, unique:true, position:"r3",Type:"TXT"},
  {label:"Une planche à voile",idQuestion:37, unique:true, position:"r4",Type:"TXT"},

  {label:"Le Pérou", idQuestion:38, unique:true, position:"r1",Type:"TXT"},
  {label:"Le Brésil", idQuestion:38,unique:true, position:"r2",Type:"TXT"},
  {label:"La Colombie", idQuestion:38, unique:true, position:"r3",Type:"TXT"},
  {label:"L'Argentine",idQuestion:38, unique:true, position:"r4",Type:"TXT"},

  {label:"François Cluzet", idQuestion:39, unique:true, position:"r1",Type:"TXT"},
  {label:"Clovis Cornillac", idQuestion:39, unique:true, position:"r2",Type:"TXT"},
  {label:"Fabrice Luchini", idQuestion:39, unique:true, position:"r3",Type:"TXT"},
  {label:"Gérard Depardieu", idQuestion:39, unique:true, position:"r4",Type:"TXT"},

  {label:"François Ier", idQuestion:40, unique:true, position:"r1",Type:"TXT"},
  {label:"Louis XIII", idQuestion:40,unique:true, position:"r2",Type:"TXT"},
  {label:"Charles VII", idQuestion:40, unique:true, position:"r3",Type:"TXT"},
  {label:"Henri II",idQuestion:40, unique:true, position:"r4",Type:"TXT"},

  {label:"Le secret de la Licorne", idQuestion:41, unique:true, position:"r1",Type:"TXT"},
  {label:"L'étoile mystérieuse", idQuestion:41,unique:true, position:"r2",Type:"TXT"},
  {label:"Le Lotus bleu", idQuestion:41, unique:true, position:"r3",Type:"TXT"},
  {label:"Le crabe aux pinces d'or",idQuestion:41, unique:true, position:"r4",Type:"TXT"},

  {label:"Les thons", idQuestion:42, unique:true, position:"r1",Type:"TXT"},
  {label:"Les raies", idQuestion:42,unique:true, position:"r2",Type:"TXT"},
  {label:"Les anguilles", idQuestion:42, unique:true, position:"r3",Type:"TXT"},
  {label:"Les requins",idQuestion:42, unique:true, position:"r4",Type:"TXT"},

  {label:"Le rugby", idQuestion:43, unique:true, position:"r1",Type:"TXT"},
  {label:"L'escrime", idQuestion:43,unique:true, position:"r2",Type:"TXT"},
  {label:"La boxe", idQuestion:43, unique:true, position:"r3",Type:"TXT"},
  {label:"Le tennis",idQuestion:43, unique:true, position:"r4",Type:"TXT"},

  {label:"Hong Kong", idQuestion:44, unique:true, position:"r1",Type:"TXT"},
  {label:"New York", idQuestion:44,unique:true, position:"r2",Type:"TXT"},
  {label:"Francfort", idQuestion:44, unique:true, position:"r3",Type:"TXT"},
  {label:"Zurich",idQuestion:44, unique:true, position:"r4",Type:"TXT"},

  {label:"Une girafe", idQuestion:45, unique:true, position:"r1",Type:"TXT"},
  {label:"Un pingouin", idQuestion:45,unique:true, position:"r2",Type:"TXT"},
  {label:"Un raton-laveur", idQuestion:45, unique:true, position:"r3",Type:"TXT"},
  {label:"Un zèbre",idQuestion:45, unique:true, position:"r4",Type:"TXT"},

  {label:"Professeur", idQuestion:46, unique:true, position:"r1",Type:"TXT"},
  {label:"Médecin", idQuestion:46,unique:true, position:"r2",Type:"TXT"},
  {label:"Avocat", idQuestion:46, unique:true, position:"r3",Type:"TXT"},
  {label:"Journaliste",idQuestion:46, unique:true, position:"r4",Type:"TXT"},

  {label:"La Flûte enchantée", idQuestion:47, unique:true, position:"r1",Type:"TXT"},
  {label:"Don Juan", idQuestion:47,unique:true, position:"r2",Type:"TXT"},
  {label:"Les Noces de Figaro", idQuestion:47, unique:true, position:"r3",Type:"TXT"},
  {label:"La Clémence de Titus",idQuestion:47, unique:true, position:"r4",Type:"TXT"},

  {label:"La graine de tournesol", idQuestion:48, unique:true, position:"r1",Type:"TXT"},
  {label:"La cacahuète", idQuestion:48,unique:true, position:"r2",Type:"TXT"},
  {label:"La pistache", idQuestion:48, unique:true, position:"r3",Type:"TXT"},
  {label:"La noix de cajou",idQuestion:48, unique:true, position:"r4",Type:"TXT"},

  {label:"Le triathlon", idQuestion:49, unique:true, position:"r1",Type:"TXT"},
  {label:"Le pentathlon", idQuestion:49,unique:true, position:"r2",Type:"TXT"},
  {label:"L'heptathlon", idQuestion:49, unique:true, position:"r3",Type:"TXT"},
  {label:"Le décathlon",idQuestion:49, unique:true, position:"r4",Type:"TXT"},

  {label:"Colombienne", idQuestion:50, unique:true, position:"r1",Type:"TXT"},
  {label:"Brésilienne", idQuestion:50,unique:true, position:"r2",Type:"TXT"},
  {label:"Argentine", idQuestion:50, unique:true, position:"r3",Type:"TXT"},
  {label:"Chilienne",idQuestion:50, unique:true, position:"r4",Type:"TXT"},

  {label:"Edit de Rethondes", idQuestion:51, unique:true, position:"r1",Type:"TXT"},
  {label:"Edit de Nantes", idQuestion:51,unique:true, position:"r2",Type:"TXT"},
  {label:"Edit de Versailles ", idQuestion:51, unique:true, position:"r3",Type:"TXT"},
  {label:"Edit de Strasbourg",idQuestion:51, unique:true, position:"r4",Type:"TXT"},

  {label:"Le twist", idQuestion:52, unique:true, position:"r1",Type:"TXT"},
  {label:"Le rock'n'roll", idQuestion:52,unique:true, position:"r2",Type:"TXT"},
  {label:"Le jazz", idQuestion:52, unique:true, position:"r3",Type:"TXT"},
  {label:"L'électro",idQuestion:52, unique:true, position:"r4",Type:"TXT"},

  {label:"0°C", idQuestion:53, unique:true, position:"r1",Type:"TXT"},
  {label:"50°C", idQuestion:53,unique:true, position:"r2",Type:"TXT"},
  {label:"100°C", idQuestion:53, unique:true, position:"r3",Type:"TXT"},
  {label:"200°C",idQuestion:53, unique:true, position:"r4",Type:"TXT"},

  {label:"Le saut en longueur", idQuestion:54, unique:true, position:"r1",Type:"TXT"},
  {label:"Le saut à la perche", idQuestion:54,unique:true, position:"r2",Type:"TXT"},
  {label:"Le triple-saut", idQuestion:54, unique:true, position:"r3",Type:"TXT"},
  {label:"Le saut en hauteur",idQuestion:54, unique:true, position:"r4",Type:"TXT"},

  {label:"Indonésie", idQuestion:55, unique:true, position:"r1",Type:"TXT"},
  {label:"Mexique", idQuestion:55,unique:true, position:"r2",Type:"TXT"},
  {label:"Inde", idQuestion:55, unique:true, position:"r3",Type:"TXT"},
  {label:"Afrique du Sud",idQuestion:55, unique:true, position:"r4",Type:"TXT"},

  {label:"Daniel Balavoine", idQuestion:56, unique:true, position:"r1",Type:"TXT"},
  {label:"Coluche", idQuestion:56,unique:true, position:"r2",Type:"TXT"},
  {label:"Thierry Le Luron", idQuestion:56, unique:true, position:"r3",Type:"TXT"},
  {label:"Yves Montand",idQuestion:56, unique:true, position:"r4",Type:"TXT"},

  {label:"Un empereur romain", idQuestion:57, unique:true, position:"r1",Type:"TXT"},
  {label:"Un astrologue", idQuestion:57,unique:true, position:"r2",Type:"TXT"},
  {label:"Un Pape", idQuestion:57, unique:true, position:"r3",Type:"TXT"},
  {label:"Un explorateur",idQuestion:57, unique:true, position:"r4",Type:"TXT"},

  {label:"J", idQuestion:58, unique:true, position:"r1",Type:"TXT"},
  {label:"M", idQuestion:58,unique:true, position:"r2",Type:"TXT"},
  {label:"S", idQuestion:58, unique:true, position:"r3",Type:"TXT"},
  {label:"V",idQuestion:58, unique:true, position:"r4",Type:"TXT"},

  {label:"2", idQuestion:59, unique:true, position:"r1",Type:"TXT"},
  {label:"3", idQuestion:59,unique:true, position:"r2",Type:"TXT"},
  {label:"4", idQuestion:59, unique:true, position:"r3",Type:"TXT"},
  {label:"5",idQuestion:59, unique:true, position:"r4",Type:"TXT"},

  {label:"Le kabuki", idQuestion:60, unique:true, position:"r1",Type:"TXT"},
  {label:"L'origami", idQuestion:60,unique:true, position:"r2",Type:"TXT"},
  {label:"L'ikebana", idQuestion:60, unique:true, position:"r3",Type:"TXT"},
  {label:"Le sashimi",idQuestion:60, unique:true, position:"r4",Type:"TXT"},

  {label:"Le Havre", idQuestion:61, unique:true, position:"r1",Type:"TXT"},
  {label:"Montpellier", idQuestion:61,unique:true, position:"r2",Type:"TXT"},
  {label:"Nice", idQuestion:61, unique:true, position:"r3",Type:"TXT"},
  {label:"Nantes",idQuestion:61, unique:true, position:"r4",Type:"TXT"},

  {label:"Kiwi", idQuestion:62, unique:true, position:"r1",Type:"TXT"},
  {label:"Sissi", idQuestion:62,unique:true, position:"r2",Type:"TXT"},
  {label:"Xana", idQuestion:62, unique:true, position:"r3",Type:"TXT"},
  {label:"Aelita",idQuestion:62, unique:true, position:"r4",Type:"TXT"},

  {label:"Première Guerre Mondiale", idQuestion:63, unique:true, position:"r1",Type:"TXT"},
  {label:"Seconde Guerre Mondiale", idQuestion:63,unique:true, position:"r2",Type:"TXT"},
  {label:"La Guerre de Cent Ans", idQuestion:63, unique:true, position:"r3",Type:"TXT"},
  {label:"La Guerre d'Espagne",idQuestion:63, unique:true, position:"r4",Type:"TXT"},

  {label:"Un Lion", idQuestion:64, unique:true, position:"r1",Type:"TXT"},
  {label:"Un Serpent", idQuestion:64,unique:true, position:"r2",Type:"TXT"},
  {label:"Un Aigle", idQuestion:64, unique:true, position:"r3",Type:"TXT"},
  {label:"Un Blaireau",idQuestion:64, unique:true, position:"r4",Type:"TXT"},

  {label:"Des enzymes", idQuestion:65, unique:true, position:"r1",Type:"TXT"},
  {label:"Des octets", idQuestion:65,unique:true, position:"r2",Type:"TXT"},
  {label:"Des pixels", idQuestion:65, unique:true, position:"r3",Type:"TXT"},
  {label:"Des bits",idQuestion:65, unique:true, position:"r4",Type:"TXT"},

  {label:"Le meilleur sprinteur", idQuestion:66, unique:true, position:"r1",Type:"TXT"},
  {label:"Le champion du monde", idQuestion:66,unique:true, position:"r2",Type:"TXT"},
  {label:"Le meilleur grimpeur", idQuestion:66, unique:true, position:"r3",Type:"TXT"},
  {label:"Le premier au classement général de la course",idQuestion:66, unique:true, position:"r4",Type:"TXT"},

];